<?php


$app_route = array(
    "dashboard" => "apps/dashboard/index.php",
    "profile" => "apps/profile/index.php",
    "users" => "apps/users/index.php",
    "users/view" => "apps/users/view.php",
    "users/add" => "apps/users/add.php",
    "users/edit" => "apps/users/edit.php",
    "users/delete" => "apps/users/delete.php",
    "system" => "apps/system/index.php",
    "category" => "apps/category/index.php",
    "category/delete" => "apps/category/delete.php",
    "driver" => "apps/driver/index.php",
    "driver/delete" => "apps/driver/delete.php",
    "place" => "apps/place/index.php",
    "place/delete" => "apps/place/delete.php",
    "type" => "apps/type/index.php",
    "type/delete" => "apps/type/delete.php",
    "status" => "apps/status/index.php",
    "status/delete" => "apps/status/delete.php",
    "brand" => "apps/brand/index.php",
    "brand/delete" => "apps/brand/delete.php",
    "inventory" => "apps/inventory/index.php",
    "inventoryby" => "apps/inventory/inventoryby.php",
    "inventory/add" => "apps/inventory/add.php",
    "inventory/edit" => "apps/inventory/edit.php",
    "inventory/history" => "apps/inventory/history.php",
    "inventory/delete" => "apps/inventory/delete.php",
    "repair" => "apps/repair/index.php",
    "repair/add" => "apps/repair/add.php",
    "repair/edit" => "apps/repair/edit.php",
    "repair/edit_job" => "apps/repair/edit_job.php",
    "repair/print" => "apps/repair/print.php",
    "usecar" => "apps/usecar/index.php",
    "usecar/add" => "apps/usecar/add.php",
    "usecar/edit" => "apps/usecar/edit.php",
    "usecar/edit_job" => "apps/usecar/edit_job.php",
    "usecar/print" => "apps/usecar/print.php",
    "problem" => "apps/problem/index.php",
    "problem/delete" => "apps/problem/delete.php",
    "language" => "apps/language/index.php",
    "department" => "apps/department/index.php",
    "department/delete" => "apps/department/delete.php",
    "report01" => "apps/report/report01.php",    
);


$app_route_js = array(
    "dashboard" => "apps/dashboard/js/index.js",
    "profile" => "apps/profile/js/index.js",
    "users" => "apps/users/js/index.js",
    "users/add" => "apps/users/js/add.js",
    "users/edit" => "apps/users/js/edit.js",
    "users/delete" => "apps/users/js/delete.js",
    "system" => "apps/system/js/index.js",
    "category" => "apps/category/js/index.js",
    "category/delete" => "apps/category/js/delete.js",
    "driver" => "apps/driver/js/index.js",
    "driver/delete" => "apps/driver/js/delete.js",
    "place" => "apps/place/js/index.js",
    "place/delete" => "apps/place/js/delete.js",
    "type" => "apps/type/js/index.js",
    "type/delete" => "apps/type/js/delete.js",
    "status" => "apps/status/js/index.js",
    "status/delete" => "apps/status/js/delete.js",
    "brand" => "apps/brand/js/index.js",
    "brand/delete" => "apps/brand/js/delete.js",
    "inventory" => "apps/inventory/js/index.js",
    "inventoryby" => "apps/inventory/js/inventoryby.js",
    "inventory/add" => "apps/inventory/js/add.js",
    "inventory/edit" => "apps/inventory/js/edit.js",
    "inventory/history" => "apps/inventory/js/history.js",
    "inventory/delete" => "apps/inventory/js/delete.js",
    "repair" => "apps/repair/js/index.js",
    "repair/add" => "apps/repair/js/add.js",
    "repair/edit" => "apps/repair/js/edit.js",
    "repair/edit_job" => "apps/repair/js/edit_job.js",
    "repair/print" => "apps/repair/js/print.js",
    "usecar" => "apps/usecar/js/index.js",
    "usecar/add" => "apps/usecar/js/add.js",
    "usecar/edit" => "apps/usecar/js/edit.js",
    "usecar/edit_job" => "apps/usecar/js/edit_job.js",
    "usecar/print" => "apps/usecar/js/print.js",
    "problem" => "apps/problem/js/index.js",
    "problem/delete" => "apps/problem/js/delete.js",
    "language" => "apps/language/js/index.js",
    "department" => "apps/department/js/index.js",
    "department/delete" => "apps/department/js/delete.js",
    "report01" => "apps/report/js/report01.js",
);







?>